services:
  instance1: &instance
    container_name: php_instance1
    image: wendellunny/php-rinha-backend-2026:1.1.2
    volumes:
      - ./php/opcache-swoole.ini:/usr/local/etc/php/conf.d/opcache-swoole.ini:ro
    deploy:
      resources:
        limits:
          cpus: '0.35'
          memory: 150M

  instance2:
    <<: *instance
    container_name: php_instance2
    
  load-balancer:
    container_name: nginx_load_balancer
    image: nginx:latest
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - instance1
      - instance2
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 50M
