services:
  instance1: &instance
    container_name: php_instance1
    image: wendellunny/php-rinha-backend-2026:1.0
    volumes:
      - ./php-ini/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini:ro
    deploy:
      resources:
        limits:
          cpus: '0.48'
          memory: 165M

  instance2:
    <<: *instance
    container_name: php_instance2
    
  load-balancer:
    container_name: nginx_load_balancer
    image: nginx:latest
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - instance1
      - instance2
    deploy:
      resources:
        limits:
          cpus: '0.04'
          memory: 20M
