worker_processes 1;

events {
    worker_connections 4096;
}

http {
    access_log off;
    error_log /var/log/nginx/error.log crit;

    upstream php_backend {
        server instance1:8080;
        server instance2:8080;
        keepalive 1024;
    }

    server {
        listen 9999;
        server_name localhost;

        location / {
            proxy_pass http://php_backend;

            proxy_http_version 1.1;
            proxy_set_header Connection "";

            proxy_connect_timeout 10s;
            proxy_send_timeout 60s;
            proxy_read_timeout 60s;

            proxy_buffering on;
            proxy_buffer_size 4k;
            proxy_buffers 4 4k;
        }
    }
}