worker_processes auto;

events {
    worker_connections 1024;
}

http {
    upstream php_backend {
        server instance1:9000;
        server instance2:9000;
    }

    server {
        listen 9999;
        server_name localhost;
        add_header X-Upstream-Addr $upstream_addr always;
        add_header X-Upstream-Status $upstream_status always;

        location / {
            include fastcgi_params;
            fastcgi_pass php_backend;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME /var/www/html/public/index.php;
            fastcgi_param SCRIPT_NAME /index.php;
        }
    }
}